import { useEffect, useMemo, useState } from "react";
import { Plus, Pin, Trash2, StickyNote } from "lucide-react";
import "./StickyNotes.css";
const KEY = "innox-sticky-notes";
function StickyNotes({ initialContent = "" }) {
  const starter = useMemo(() => [{ id: "recruiter-guide", title: "Welcome, recruiter", content: initialContent || "Welcome to Jacob's portfolio desktop.\n\nStart with the Profile app to learn about Jacob, then open Projects to explore Auri, Natter, and other work.\n\nTip: use the taskbar search, double-click desktop icons, and try the voice assistant. You can read the CV and Resume in Notepad.\n\nThis is a simulated operating system built with React.", color: "yellow", pinned: true }], []);
  const [notes, setNotes] = useState(() => { try { const saved = JSON.parse(localStorage.getItem(KEY)); return Array.isArray(saved) ? saved : starter; } catch { return starter; } });
  const [activeId, setActiveId] = useState(notes[0]?.id);
  const [editingTitle, setEditingTitle] = useState(false);
  const active = notes.find((note) => note.id === activeId) || notes[0];
  useEffect(() => { localStorage.setItem(KEY, JSON.stringify(notes)); }, [notes]);
  const updateActive = (updates) => setNotes((items) => items.map((note) => note.id === active?.id ? { ...note, ...updates } : note));
  const createNote = () => { const note = { id: `note-${Date.now()}`, title: "Untitled note", content: "", color: ["yellow", "pink", "blue", "green"][notes.length % 4], pinned: false }; setNotes((items) => [note, ...items]); setActiveId(note.id); setEditingTitle(true); };
  const deleteNote = () => { if (!active) return; const remaining = notes.filter((note) => note.id !== active.id); setNotes(remaining); if (remaining.length) setActiveId(remaining[0].id); else { setNotes([]); setActiveId(null); } };
  const ordered = [...notes].sort((a, b) => Number(b.pinned) - Number(a.pinned));
  return <section className="sticky-app"><aside className="sticky-sidebar"><div className="sticky-sidebar-head"><div><StickyNote size={17} /><strong>Sticky Notes</strong></div><button type="button" onClick={createNote} title="New note"><Plus size={17} /></button></div><div className="sticky-note-list">{ordered.map((note) => <button type="button" key={note.id} className={`sticky-note-item ${note.id === active?.id ? "active" : ""}`} onClick={() => setActiveId(note.id)}><span className={`sticky-color-dot ${note.color}`} />{note.pinned && <Pin size={11} />}<span><strong>{note.title || "Untitled note"}</strong><small>{note.content.slice(0, 48) || "No additional text"}</small></span></button>)}{!ordered.length && <div className="sticky-empty-list">Your notes will appear here.</div>}</div><div className="sticky-sidebar-foot">{notes.length} {notes.length === 1 ? "note" : "notes"} | saved on this device</div></aside>
  {active ? <article className={`sticky-paper ${active.color}`}><header><div>{editingTitle ? <input autoFocus value={active.title} onChange={(event) => updateActive({ title: event.target.value })} onBlur={() => setEditingTitle(false)} onKeyDown={(event) => event.key === "Enter" && setEditingTitle(false)} /> : <button className="sticky-title-button" onClick={() => setEditingTitle(true)} title="Rename note">{active.title || "Untitled note"}</button>}<small>Saved automatically</small></div><div className="sticky-tools"><button type="button" className={active.pinned ? "pinned" : ""} onClick={() => updateActive({ pinned: !active.pinned })} title={active.pinned ? "Unpin note" : "Pin note"}><Pin size={15} /></button><select aria-label="Note color" value={active.color} onChange={(event) => updateActive({ color: event.target.value })}><option value="yellow">Sunshine</option><option value="pink">Rose</option><option value="blue">Sky</option><option value="green">Mint</option></select><button type="button" onClick={deleteNote} title="Delete note"><Trash2 size={15} /></button></div></header><textarea aria-label="Note text" value={active.content} placeholder="Write a note..." onChange={(event) => updateActive({ content: event.target.value })} /></article> : <button type="button" className="sticky-create-empty" onClick={createNote}><Plus size={17} /> Create your first note</button>}</section>;
}
export default StickyNotes;
