import { useMemo, useState } from "react";
import { Archive, Inbox, Mail, MoreHorizontal, Paperclip, Plus, Reply, Search, Send, Star, Trash2, X } from "lucide-react";
import "./Email.css";
const SEED = [
  { id: 1, from: "Jacob Mongolo", email: "jakemongolo4@gmail.com", subject: "Welcome to my portfolio", preview: "Thanks for taking the time to explore my interactive desktop.", body: `Hello,\n\nThanks for visiting my portfolio. I built this desktop to make exploring my projects and experience a little more memorable.\n\nYou can use the Profile and Projects apps to get started.\n\nBest,\nJacob`, date: "Today", unread: true, starred: true },
  { id: 2, from: "Innoxation Projects", email: "projects@innoxation.dev", subject: "Auri project overview", preview: "A look at the product direction, core features, and technology behind Auri.", body: "Auri is a calmer social and entertainment experience, designed around intentional interaction and community.", date: "Yesterday", unread: true },
  { id: 3, from: "Portfolio Updates", email: "updates@innoxation.dev", subject: "New work and technologies", preview: "Recent work spans React Native, full-stack product development, and AI experiences.", body: "Jacob's recent work covers mobile and web development, backend services, design systems, and AI-assisted experiences.", date: "Tue", unread: false },
  { id: 4, from: "Natter Team", email: "hello@natter.app", subject: "Natter: privacy-first social", preview: "A social platform focused on meaningful communication and privacy.", body: "Natter is an Innoxation project focused on privacy, communication, and a more intentional social experience.", date: "Mongolo", unread: false },
];

function Email() {
  const [messages, setMessages] = useState(SEED);
  const [selectedId, setSelectedId] = useState(SEED[0].id);
  const [query, setQuery] = useState("");
  const [compose, setCompose] = useState(false);
  const [to, setTo] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  const selected = messages.find((item) => item.id === selectedId);
  const visible = useMemo(() => messages.filter((item) => `${item.from} ${item.subject} ${item.preview}`.toLowerCase().includes(query.toLowerCase())), [messages, query]);
  const markRead = (id) => setMessages((items) => items.map((item) => item.id === id ? { ...item, unread: false } : item));
  const send = (event) => { event.preventDefault(); const target = to.trim() || "jakemongolo4@gmail.com"; window.location.href = `mailto:${encodeURIComponent(target)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; setCompose(false); };
  return <section className="outlook-app"><header className="outlook-topbar"><div className="outlook-brand"><span><Mail size={17} /></span><strong>Outlook</strong></div><label className="outlook-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search mail" /></label><button className="outlook-compose" onClick={() => setCompose(true)}><Plus size={15} /> New message</button></header>
    <div className="outlook-layout"><aside className="outlook-folders"><button className="outlook-folder active"><Inbox size={16} /><span>Inbox</span><b>{messages.filter((m) => m.unread).length}</b></button><button className="outlook-folder"><Star size={16} /><span>Starred</span></button><button className="outlook-folder"><Send size={16} /><span>Sent</span></button><button className="outlook-folder"><Archive size={16} /><span>Archive</span></button><div className="outlook-account"><div>JM</div><span><strong>Jacob Mongolo</strong><small>Portfolio inbox</small></span></div></aside>
    <div className="outlook-inbox"><div className="outlook-inbox-heading"><div><strong>Inbox</strong><small>{visible.length} messages</small></div><button title="More options"><MoreHorizontal size={17} /></button></div><div className="outlook-message-list">{visible.map((message) => <button key={message.id} className={`outlook-message-row ${selectedId === message.id ? "selected" : ""} ${message.unread ? "unread" : ""}`} onClick={() => { setSelectedId(message.id); markRead(message.id); }}><span className="outlook-avatar">{message.from.slice(0, 1)}</span><span className="outlook-row-copy"><strong>{message.from}</strong><b>{message.subject}</b><small>{message.preview}</small></span><span className="outlook-row-date">{message.date}{message.starred && <Star size={12} fill="currentColor" />}</span></button>)}{!visible.length && <div className="outlook-empty">No messages match your search.</div>}</div></div>
    <article className="outlook-reading">{selected ? <><header className="outlook-reading-head"><div><span className="outlook-subject-mark"><Mail size={17} /></span><h1>{selected.subject}</h1></div><div><button title="Archive"><Archive size={15} /></button><button title="Delete"><Trash2 size={15} /></button><button title="More"><MoreHorizontal size={16} /></button></div></header><div className="outlook-sender"><span className="outlook-avatar large">{selected.from.slice(0, 1)}</span><div><strong>{selected.from}</strong><small>&lt;{selected.email}&gt;</small><small>To: Jacob Mongolo</small></div><time>{selected.date}</time></div><div className="outlook-message-body">{selected.body}</div><button className="outlook-reply" onClick={() => { setTo(selected.email); setSubject(`Re: ${selected.subject}`); setCompose(true); }}><Reply size={15} /> Reply</button></> : <div className="outlook-empty">Select a message to read it.</div>}</article></div>
    {compose && <div className="outlook-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setCompose(false)}><form className="outlook-compose-modal" onSubmit={send}><header><strong>New message</strong><button type="button" onClick={() => setCompose(false)} aria-label="Close"><X size={17} /></button></header><label>To<input type="email" value={to} onChange={(e) => setTo(e.target.value)} placeholder="recipient@example.com" /></label><label>Subject<input value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Add a subject" /></label><textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder="Write your message..." /><footer><button className="outlook-send" type="submit"><Send size={14} /> Send</button><button className="outlook-attach" type="button" title="Attachments are not available in this demo"><Paperclip size={15} /></button><button className="outlook-discard" type="button" onClick={() => setCompose(false)}><Trash2 size={15} /></button></footer></form></div>}
  </section>;
}
export default Email;
